[build]
  Functions = "netlify-functions/lambda"
  Command = "npm run build:lambda"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"